config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, only: [:show, :edit, :index, :update]

  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resource :favorite, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  root to: "homes#top"
  get "home/about" => "homes#about"


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: {maximum:200}

  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end


end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :comment, presence: true

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
  
  validates :user_id, uniqueness: {scope: :book_id}
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, uniqueness: true
  validates :name, length: {minimum:2, maximum:20}


  validates :introduction, length: {maximum:50}

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_one_attached :profile_image

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join("app/assets/images/default-image.jpg")
      profile_image.attach(io: File.open(file_path), filename: "default-image.jpg", content_type: "image/jpeg")
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, except: [:top, :about]

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end



  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:email, :name])
  end

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_to book_path(book)
  end

  def destroy
    BookComment.find(params[:id]).destroy
    redirect_to book_path(params[:book_id])
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end


end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @user = User.find(current_user.id)
      @books = Book.all
      render :index
    end
  end

  def index
    @book = Book.new
    @user = User.find(current_user.id)
    @books = Book.all
    @book_comment = BookComment.new
  end

  def show
    @book = Book.find(params[:id])
    @user = User.find(@book.user_id)
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
    if current_user != @book.user
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(params[:id])
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_to request.referer
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_to request.referer
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]

  def index
    @user = User.find(current_user.id)
    @users = User.all
  end


  def show
    @user = User.find(params[:id])
    @books = Book.where(user_id: params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(current_user.id)
    else
      render :edit
    end
  end

private

def user_params
  params.require(:user).permit(:name, :introduction, :profile_image)
end

def is_matching_login_user
  user = User.find(params[:id])
  login_user = current_user
  if (user.id != login_user.id)
    redirect_to user_path(current_user)
  end
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_left.html.erb
<div class="col-md-3">
    <h2>User info</h2>
    <%= image_tag user.get_profile_image(100, 100) %>
    <table class="table">
        <tbody>
            <tr>
                <th>name</th>
                <th><%= user.name %></th>
            </tr>
            <tr>
                <th>introduction</th>
                <th><%= user.introduction %></th>
            </tr>
        </tbody>
    </table>
    <div class="row">
        <a class="btn btn-outline-secondary btn-block" href="/users/<%= user.id %>/edit">
            <i class="fa-solid fa-user-gear"></i>
        </a>
    </div>
<h2 class="mt-3">New book</h2>
    <%= form_with url: books_path, model: Book.new do |f| %>
        <div class="form-group">
            <h6>Title</h6>
            <%= f.text_field :title %>
        </div>
        <div class="form-group">
            <h6>Opinion</h6>
            <%= f.text_area :body %>
        </div>
        <div class="form-group">
            <%= f.submit "Create Book", class: "btn btn-success" %>
        </div>
    <% end %>
</div>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <% if @book.errors.any? %>
        <div class="error_explanation">
          <h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
          <ul>
            <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%= form_with url: book_path, model: @book do |f| %>
        <div class="form-group">
          <h6>Title</h6>
          <%= f.text_field :title %>
        </div>
        <div class="form-group">
          <h6>Opinion</h6>
          <%= f.text_area :body  %>
        </div>
        <div class="form-group">
          <%= f.submit "Update Book", class: "btn btn-success" %>
        </div>
      <% end %>
      <%= link_to "Show", book_path(params[:id]) %>
      |
      <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
    <% if @book.errors.any? %>
        <div class="error_explanation">
            <h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
            <ul>
                <% @book.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <div class="row">
        <%= render "left", user: @user %>
        <div class="col-md-8 offset-md-1">
            <h2>Books</h2>
            <table class="table table-hover table-inverse">
                <thead>
                    <tr>
                        <th></th>
                        <th>Title</th>
                        <th>Opinion</th>
                        <th colspan="3"></th>
                    </tr>
                </thead>
                <% @books.each do |book| %>
                    <tbody>
                        <tr>
                            <td>
                                <%= link_to user_path(book.user_id) do %>
                                    <%= image_tag User.find(book.user_id).get_profile_image(100, 100) %>
                                <% end %>
                            </td>
                            <td>
                                <%= link_to book_path(book.id) do %>
                                    <%= book.title %>
                                <% end %>
                            </td>
                            <td>
                                <%= book.body %>
                            </td>
                            <td>
                                <% if  book.favorited_by?(current_user) %>
                                    <p>
                                        <%= link_to book_favorite_path(book), method: :delete do %>
                                            <i class="fa-solid fa-heart", style="color: red"></i><%= book.favorites.count %> likes
                                        <% end %>
                                    </p>
                                <% else %>
                                    <p>
                                <%= link_to book_favorite_path(book), method: :post do%>
                                    <i class="fa-regular fa-heart", style="color: red"></i><%= book.favorites.count %> likes
                                <% end %>
                                    </p>
                                <% end %>
                            </td>
                        </tr>
                    </tbody>
                <% end %>
            </table>
        </div>
    </div>
</div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
    <div class="row">
        <%= render "books/left", user: @user %>
        <div class="col-md-8 offset-md-1">
            <h2>Book detail</h2>
            <table class="table">
                <tbody>
                    <tr>
                        <td>
                            <%= link_to user_path(@book.user_id) do %>
                                <%= image_tag @book.user.get_profile_image(100, 100) %>
                                <br>
                                <%= @book.user.name %>
                            <% end %>
                        </td>
                        <td>
                            <%= link_to book_path(@book.id) do %>
                                <%= @book.title %>
                            <% end %>
                        </td>
                        <td>
                            <%= @book.body %>
                        </td>
                        <td>
                            <% if  @book.favorited_by?(current_user) %>
                                <p>
                                    <%= link_to book_favorite_path(@book), method: :delete do %>
                                        <i class="fa-solid fa-heart", style="color: red"></i><%= @book.favorites.count %> likes
                                    <% end %>
                                </p>
                            <% else %>
                                <p>
                                    <%= link_to book_favorite_path(@book), method: :post do%>
                                        <i class="fa-regular fa-heart", style="color: red"></i><%= @book.favorites.count %> likes
                                    <% end %>
                                </p>
                            <% end %>
                        </td>
                        <% if @book.user_id == current_user.id %>
                        <td>
                            <%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-success"  %>
                        </td>
                        <td>
                            <%= link_to "Destroy", book_path(@book.id), method: :delete, data: {confirm: "本当に消しますか？"}, class: "btn btn-danger" %>
                        </td>
                        <% end %>
                    </tr>
                </tbody>
            </table>
            <h3>Comment</h3>
            <p>Number of comments: <%= @book.book_comments.count %></p>
            <table class="table">
                <tbody>
                <% @book.book_comments.each do |book_comment| %>
                    <tr>
                        <td>
                            <%= link_to user_path(book_comment.user) do %>
                                <%= image_tag book_comment.user.get_profile_image(70, 70) %><br>
                                <%= book_comment.user.name %>
                            <% end %>
                        </td>
                        <td>
                            <%= book_comment.comment %>
                        </td>
                        <td>
                            <%= book_comment.created_at.strftime('%Y/%m/%d') %>
                        </td>
                        <td>
                            <% if book_comment.user ==current_user %>
                                <%= link_to "Destroy",book_book_comment_path(book_comment.book, book_comment), method: :delete, data: {confirm: "本当に消しますか？"}, class: "btn btn-danger" %>
                            <% end %>
                        </td>
                    </tr>
                <% end %>
                </tbody>
            </table>
            <h2 class="mt-3">New Comment</h2>
            <%= form_with model: [@book, @book_comment] do |f| %>
                <div class="form-group"</div>
                    <h6 class="book_comment">Comment</h6>
                    <%= f.text_area :comment, rows: "3",class: "form-control", id: "book_comment" %>
                </div>
                <div class="form-group">
                    <%= f.submit "送信", class: "btn btn-success" %>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/homes/about.html.erb
<div class="container">
    <div class="row">
        <div class="mx-auto px-3">
            <h1>
                Welcome to <i class="fa-solid fa-book"></i><strong>Bookers!</strong>
            </h1>
        </div>
    </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>
        welcome to <i class="fa-solid fa-book"></i><strong>Boookers !!</strong>
      </h1>
      <p>
        In <i class="fa-solid fa-book"></i><strong>Bookers</strong>
      </p>
      <p>you can share and exchange your opinions, inpressions and emotions <br> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
        </div>
        <div class="row">
          <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

          <script src="https://kit.fontawesome.com/73336f91b7.js" crossorigin="anonymous"></script>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">Bookers</a>
        </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li>
                <%= link_to user_path(current_user), class: "nav-link text-light" do %>
                  <i class="fas fa-home"></i> Home
                <% end %>
              </li>
              <li>
                <%= link_to users_path, class: "nav-link text-light" do %>
                  <i class="fas fa-users"></i> Users
                <% end %>
              </li>
              <li>
                <%= link_to books_path, class: "nav-link text-light" do %>
                  <i class="fas fa-book-open"></i> Books
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete, class: "nav-link text-light" do %>
                  <i class="fas fa-sign-out-alt"></i> Log out
                <% end %>
              </li>
            <% else %>
              <li>
                <%= link_to root_path, class: "nav-link text-light" do %>
                  <i class="fas fa-home"></i> Home
                <% end %>
              </li>
              <li>
                <%= link_to home_about_path, class: "nav-link text-light" do %>
                  <i class="fas fa-link"></i> About
                <% end %>
              </li>
              <li>
                <%= link_to new_user_registration_path, class: "nav-link text-light" do %>
                  <i class="fas fa-user-plus"></i> Sign up
                <% end %>
              </li>
              <li>
                <%= link_to new_user_session_path, class: "nav-link text-light" do %>
                  <i class="fas fa-sign-in-alt"></i> Log in
                <% end %>
              </li>
            <% end %>
          </ul>
        </div>
      </nav>
    </header>
      <%= flash[:notice] %>
    </p>
    <%= yield %>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <% if @user.errors.any? %>
        <div class="error_explanation">
          <h3><%= @user.errors.count %>errors prohibited this obj from being saved:</h3>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%= form_with model: @user do |f| %>
        <div class="form-group">
          <h6 for="user_name">Name</h6>
          <%= f.text_field :name, id: "user_name" %>
        </div>
        <div class="form-group">
          <h6 for="user_image">Image</h6>
          <%= f.file_field :profile_image, accept: "image/*", id: "user_profile_image" %>
        </div>
        <div class="form-group">
          <h6 for="user_introduction">Introduction</h6>
          <%= f.text_area :introduction, id: "user_introduction" %>
        </div>
        <%= f.submit "Update User", class: "btn btn-secondary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render "books/left", user: @user %>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <% @users.each do |user| %>
          <tbody>
            <tr>
              <td>
                <%= image_tag user.get_profile_image(100, 100) %>
              </td>
              <td>
                <%= user.name %>
              </td>
              <td>
                <%= link_to "Show", user_path(user.id) %>
              </td>
            </tr>
          </tbody>
      <% end %>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
    <div class="row">
        <%= render "books/left", user: @user %>
        <div class="col-md-8 offset-md-1">
            <h2>Books</h2>
            <table class="table table-hover table-inverse">
                <thead>
                    <tr>
                        <th></th>
                        <th>Title</th>
                        <th>Opinion</th>
                        <th colspan="3"></th>
                    </tr>
                </thead>
                <% @books.each do |book| %>
                    <tbody>
                        <tr>
                            <td>
                                <%= link_to user_path(book.user_id) do %>
                                    <%= image_tag book.user.get_profile_image(100, 100) %>
                                <% end %>
                            </td>
                            <td>
                                <%= link_to book_path(book.id) do %>
                                    <%= book.title %>
                                <% end %>
                            </td>
                            <td>
                                <%= book.body %>
                            </td>
                            <td>
                                <% if  book.favorited_by?(current_user) %>
                                    <p>
                                        <%= link_to book_favorite_path(book), method: :delete do %>
                                            <i class="fa-solid fa-heart", style="color: red"></i><%= book.favorites.count %> likes
                                        <% end %>
                                    </p>
                                <% else %>
                                    <p>
                                <%= link_to book_favorite_path(book), method: :post do%>
                                    <i class="fa-regular fa-heart", style="color: red"></i><%= book.favorites.count %> likes
                                <% end %>
                                    </p>
                                <% end %>
                            </td>
                        </tr>
                    </tbody>
                <% end %>
            </table>
        </div>
    </div>
</div>